# ArgoCD Application for Jellyfin
# Prerequisites: See manifests/jellyfin/README.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexserra98/k8s-components-home-lab.git
    targetRevision: main
    path: manifests/jellyfin
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
