# ArgoCD Application for qBittorrent
# Prerequisites: See manifests/qbittorrent/README.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexserra98/k8s-components-home-lab.git
    targetRevision: main
    path: manifests/qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
